server:
  port: 8082

spring:
  application:
    name: gestionEquip
  main:
    web-application-type: reactive
  datasource:
    url: jdbc:postgresql://localhost:5432/mytech
    username: postgres
    password : password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/