spring:
  application:
    name: gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: gestion
          uri: lb://gestionEquip
          predicates:
            - Path=/gestionEquip/**
        - id: auth
          uri: lb://authentification
          predicates:
            - Path=/authentification/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  registerWithEureka: false
  fetchRegistry: false

