server:
  port: 8761

spring:
  application:
    name: eurekaS

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry : false
    register-with-eureka : false
    serviceUrl:
      defaultZone : http://localhost:8761/eurekaS/
