server:
  port: 8081


spring:
  application:
    name: authentification
  main:
    web-application-type: reactive
  datasource:
    url: jdbc:postgresql://localhost:5432/mytech
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/